/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as CvesIndexRouteImport } from './routes/cves.index'
import { Route as CvesIdRouteImport } from './routes/cves.$id'
import { Route as MisconfigsIndexRouteImport } from './routes/misconfigs.index'
import { Route as MisconfigsSlugRouteImport } from './routes/misconfigs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const CvesIndexRoute = CvesIndexRouteImport.update({
  id: '/cves/',
  path: '/cves/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvesIdRoute = CvesIdRouteImport.update({
  id: '/cves/$id',
  path: '/cves/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MisconfigsIndexRoute = MisconfigsIndexRouteImport.update({
  id: '/misconfigs/',
  path: '/misconfigs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisconfigsSlugRoute = MisconfigsSlugRouteImport.update({
  id: '/misconfigs/$slug',
  path: '/misconfigs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/watch': typeof WatchRoute
  '/cves/$id': typeof CvesIdRoute
  '/misconfigs/$slug': typeof MisconfigsSlugRoute
  '/cves/': typeof CvesIndexRoute
  '/misconfigs/': typeof MisconfigsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/watch': typeof WatchRoute
  '/cves/$id': typeof CvesIdRoute
  '/misconfigs/$slug': typeof MisconfigsSlugRoute
  '/cves': typeof CvesIndexRoute
  '/misconfigs': typeof MisconfigsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/headers': typeof HeadersRoute
  '/watch': typeof WatchRoute
  '/cves/$id': typeof CvesIdRoute
  '/misconfigs/$slug': typeof MisconfigsSlugRoute
  '/cves/': typeof CvesIndexRoute
  '/misconfigs/': typeof MisconfigsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/headers'
    | '/watch'
    | '/cves/$id'
    | '/misconfigs/$slug'
    | '/cves/'
    | '/misconfigs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/headers'
    | '/watch'
    | '/cves/$id'
    | '/misconfigs/$slug'
    | '/cves'
    | '/misconfigs'
  id:
    | '__root__'
    | '/'
    | '/headers'
    | '/watch'
    | '/cves/$id'
    | '/misconfigs/$slug'
    | '/cves/'
    | '/misconfigs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeadersRoute: typeof HeadersRoute
  WatchRoute: typeof WatchRoute
  CvesIdRoute: typeof CvesIdRoute
  MisconfigsSlugRoute: typeof MisconfigsSlugRoute
  CvesIndexRoute: typeof CvesIndexRoute
  MisconfigsIndexRoute: typeof MisconfigsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cves/': {
      id: '/cves/'
      path: '/cves'
      fullPath: '/cves/'
      preLoaderRoute: typeof CvesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cves/$id': {
      id: '/cves/$id'
      path: '/cves/$id'
      fullPath: '/cves/$id'
      preLoaderRoute: typeof CvesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misconfigs/': {
      id: '/misconfigs/'
      path: '/misconfigs'
      fullPath: '/misconfigs/'
      preLoaderRoute: typeof MisconfigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misconfigs/$slug': {
      id: '/misconfigs/$slug'
      path: '/misconfigs/$slug'
      fullPath: '/misconfigs/$slug'
      preLoaderRoute: typeof MisconfigsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeadersRoute: HeadersRoute,
  WatchRoute: WatchRoute,
  CvesIdRoute: CvesIdRoute,
  MisconfigsSlugRoute: MisconfigsSlugRoute,
  CvesIndexRoute: CvesIndexRoute,
  MisconfigsIndexRoute: MisconfigsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
